### ISSUE TITLE
Setup Jest for Nest Frontend

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#79]
This task aims to set up **Jest** as the testing framework for the frontend of our monorepo, with tests placed in a dedicated `__tests__` directory at the root level of the project. This structure ensures a clear separation between source code and tests while maintaining organized and scalable project files.  

---

#### **1. Install Jest and Related Dependencies**  
1. Install Jest and necessary testing utilities:  
   ```bash
   npm install jest @testing-library/react @testing-library/jest-dom @testing-library/user-event ts-jest @types/jest --save-dev
   ```

2. Initialize Jest configuration:  
   ```bash
   npx ts-jest config:init
   ```
   This will create a `jest.config.js` file optimized for TypeScript.

---

#### **2. Configure Jest**  
1. Update the `jest.config.js` file to support the test directory at the root level:  
   ```javascript
   module.exports = {
     preset: "ts-jest",
     testEnvironment: "jsdom",
     setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
     moduleNameMapper: {
       "^.+\\.css$": "identity-obj-proxy",
       "^.+\\.(png|jpg|jpeg|gif|svg)$": "<rootDir>/__mocks__/fileMock.js"
     },
     transform: {
       "^.+\\.tsx?$": "ts-jest"
     },
     moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
     testMatch: ["<rootDir>/__tests__/**/*.(test|spec).{ts,tsx}"]
   };
   ```

2. Create a `jest.setup.js` file for custom test configurations:  
   ```javascript
   import '@testing-library/jest-dom';
   ```

3. Add a mock file for static asset imports in `__mocks__/fileMock.js`:  
   ```javascript
   module.exports = 'test-file-stub';
   ```

---

#### **3. Write a Sample Test**  
1. Create the `__tests__` directory at the root level of the repository:  
   ```plaintext
   project-root/
   ├── src/
   │   ├── components/
   │   │   ├── App.tsx
   │   │   ├── ...
   │   ├── ...
   ├── __tests__/
   │   ├── App.test.tsx
   ├── package.json
   ├── jest.config.js
   ├── ...
   ```

2. Add a basic test in `__tests__/App.test.tsx`:  
   ```tsx
   import React from "react";
   import { render, screen } from "@testing-library/react";
   import App from "../src/components/App";

   test("renders learn react link", () => {
     render(<App />);
     const linkElement = screen.getByText(/learn react/i);
     expect(linkElement).toBeInTheDocument();
   });
   ```

---

#### **4. Add Test Scripts**  
Update `package.json` with Jest scripts:  
```json
{
  "scripts": {
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage"
  }
}
```

---

#### **5. Add GitHub Actions for CI/CD**  
1. Create a workflow file at `.github/workflows/test.yml`.  

2. Add the following configuration:  
   ```yaml
   name: Run Tests

   on:
     pull_request:
       branches:
         - main
     push:
       branches:
         - main

   jobs:
     run-tests:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
             node-version: 18
             cache: 'npm'

         - name: Install Dependencies
           run: npm install

         - name: Run Jest Tests
           run: npm run test -- --ci
   ```

---

#### **6. Update Documentation**  
- Add a section in the README for testing instructions:  
  - Run all tests: `npm run test`  
  - Watch tests: `npm run test:watch`  
  - Check coverage: `npm run test:coverage`  
- Include a note about the location of the `__tests__` directory.

---

### **Acceptance Criteria**  
- Jest is installed and configured for the frontend package.  
- A `__tests__` directory exists at the root level, and sample tests run successfully.  
- GitHub Actions workflow runs Jest tests on `push` and `pull_request` events.  
- Workflow fails on test errors and passes when all tests succeed.  
- Documentation is updated with test-related instructions.
